name: builds

on:
  push:
    branches: [main]
    paths:
      - "src/**.py"
      - "setup.py"
      - "setup.cfg"
      - ".github/workflows/build.yml"
  pull_request:
    branches-ignore: ["**docker**"]
    paths:
      - "src/**.py"
      - "setup.py"
      - "setup.cfg"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    name: Test build process
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade python setuptools
        run: |
          pip install --upgrade pip
          pip install --upgrade wheel setuptools setuptools_scm

      - name: Inspect version info
        run: |
          python setup.py --version
          git describe --dirty --tags --long --match "*[0-9]*"

      - name: Test pip install syntax
        run: |
          pip install .
          pip uninstall -y mud-examples

      - name: Test build
        run: |
          python setup.py sdist bdist_wheel
          pip uninstall -y mud-examples
