name: DockerHub

on:
  # push:
  #   branches: [ main, dev ]

  schedule:
      - cron: "0 0 */7 * *"

  push_to_dockerhub:
    name: Publish Latest 
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          cd bin
          make
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mathematicalmichael/mud
          tag_with_ref: true
