name: DockerHub

on:
  release:
    types: [published, created, edited]
  push:
    branches: 'feature/docker'

jobs:

  push_to_github:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          build-args: 'USER_ID=1000,GROUP_ID=1000'

  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bin/Dockerfile
          push: true
          tags: mathematicalmichael/mudex:latest
          build-args: 'USER_ID=1000,GROUP_ID=1000'

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # push_to_dockerhub:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Build Docker Image
  #       run: |
  #         echo "Sleeping for a minute to allow pypi to update."
  #         sleep 60
  #         cd bin
  #         make
        
  #     - name: Push to Docker Hub
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: mathematicalmichael/mud
  #         tag_with_ref: true
