name: examples

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
  schedule:
      - cron: "0 0 1 * *"

jobs:
  pip-build:
    name: Default ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [3.6, 3.9]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install .

      - name: Test CLI
        run: |
          cd /tmp
          mud_run_all
  
      - name: Generate figures using makefile
        run: |
          cd scripts
          make clean
          make ode-examples

  conda-build:
    name: Conda ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
 
      - name: Fenics install
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          conda env update --file environment.yml --name base

      - name: Install Dependencies
        run: |
          pip install .

      - name: Conda information
        run: conda list

      - name: Test that command-line scripts installed
        run: |
          cd /tmp
          mud_run_all

      - name: Generate figures using Makefile
        run: |
          cd scripts
          make clean
          make pde-examples
          make examples

      - name: Tests
        run: |
          pip install -e .[test]
          pytest

      - name: Tests without packaged files
        run: |
          rm src/mud_examples/data/pde_2D/*
          pytest

      - name: CodeCov.io Report
        if: ${{ matrix.python-version }} == 3.8
        run: |
          # coverage run --source=. -m py.test
          coverage report -m
          bash <(curl -s https://codecov.io/bash) 
